### ISSUE TITLE
Service 'playground' failed to build

### ISSUE THREAD

**Issue by madhusudhan1234** [gcamrit/docker-homestead#1]
ERROR: Service 'playground' failed to build: The command '/bin/sh -c apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by madhusudhan1234** [comment]
Last Lines during build of playground service are as follows


W: chmod 0700 of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/cache/apt/archives/lock - open (13: Permission denied)
E: Unable to lock directory /var/cache/apt/archives/
W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
ERROR: Service 'playground' failed to build: The command '/bin/sh -c apt-get clean && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by gcamrit** [comment]
i have update the docker files and docker-compose version and unable to recreate the issue. Please pull the latest changes and try again. please let me know if it doesn't work for you.

Thanks

**Comment by madhusudhan1234** [comment]
Okay sure ! Thank you .
