### ISSUE TITLE
Example nginx config file

### ISSUE THREAD

**Issue by madhusudhan1234** [gcamrit/docker-homestead#2]
I am really interested to add one example nginx config file, which helps other devs to get quick start with the docker environment.

**Comment by gcamrit** [comment]
welcome for the pr

**Comment by madhusudhan1234** [comment]
Hello @gcamrit  dai, What is the best way to switch between php7.2.2 and php7.1 version by using docker-homestaed ? would you like to say something about it .

**Comment by gcamrit** [comment]
on port 80 the app will open on php 7.2 and on port 81 app will run in php7.1
